server:
  port: 8385
# Oracle Connect
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scottJpa
    password: tiger
# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none