# http port set
server:
  port: 8386
  
spring:
  #File Size
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
# Oracle Connect
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    password: tiger

# gmail Transfer
  mail:
    host: smtp.gmail.com
    port: 587
    username: card3351@gmail.com
    password: gus979582
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
# ORM JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# view resolver(Templete -> JSP Use)#성현이 화이팅!!
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

# Mybatis
mybatis:
  # dto Location
  # type-aliases-package: com.oracle.oBootMybatis03.model
  # xml location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml